name: PR Verify

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: PR Verify
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: Build with dotnet Linux x64
        run: dotnet build --configuration Release --runtime linux-x64 --self-contained false

      - name: dotnetTest
        run: dotnet test --configuration Release --no-build
